name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # init and download dependencies
      - name: Init and download dependencies
        run: go mod init financial-api && go mod download && go mod tidy

      # install swag CLI
      - name: Install Swag CLI
        run: go install github.com/swaggo/swag/cmd/swag@latest

      # generate swagger documentation
      - name: Generate Swagger documentation
        run: swag init

      # build project
      - name: Build project
        run: go build
      
      # run tests
      - name: Run tests
        run: go test -v ./...
