name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2.4.2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.6.0
      with:
        node-version: 16

    - name: Set up Go
      uses: actions/setup-go@v2.1.5
      with:
        go-version: 1.19

    - name: Install dependencies
      run: go mod download

    - name: Build project
      run: go build

    - name: Run tests
      run: go test -v ./...
