name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install dependencies
        run: go mod download

      - name: Install Swag CLI
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Generate Swagger documentation
        run: swag init

      - name: Build project
        run: go build

      - name: Run tests
        run: go test -v ./...
