name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build app and db images
      run: |
        docker-compose -f docker-compose.yml build
      
    - name: Test app and db
      run: |
        docker-compose -f docker-compose.yml up -d db
        sleep 10
        docker-compose -f docker-compose.yml run --rm app go test -v ./...
        docker-compose -f docker-compose.yml down
