name: Generate Swagger Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-swagger:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install Swag CLI
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Generate Swagger documentation
        run: swag init
